---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install unzip if not present
      apt:
        name: unzip
        state: present

    - name: Download AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip the AWS CLI package
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Run the AWS CLI installation script
      command:
        cmd: sudo /tmp/aws/install
        creates: /usr/local/aws-cli

    - name: Verify AWS CLI v2 installation
      command: /usr/local/bin/aws --version
...

